---
# TODO: improve ssh hardening
# hardening points: https://dev-sec.io/baselines/ssh/
# also see: https://galaxy.ansible.com/dev-sec/ssh-hardening
- name: Copy ssh public keys
  template:
    src: authorized_keys.j2
    dest: "{{ ssh_authorized_keys_path }}"
    owner: root
    group: root
    mode: 0755
  register: _ssh_keys

- name: "[etc/ssh/sshd_config] Deactivate PermitRootLogin"
  replace:
    path: /etc/ssh/sshd_config
    regexp: "#PermitRootLogin prohibit-password"
    replace: "PermitRootLogin no"
  register: _ssh_permit_rootlogin

- name: "[etc/ssh/sshd_config] Deactivate PasswordAuthentication"
  replace:
    path: /etc/ssh/sshd_config
    regexp: "#PasswordAuthentication yes"
    replace: "PasswordAuthentication no"
  register: _ssh_pw_auth

- name: Restart sshd service
  service:
    name: ssh
    state: restarted
  when: >
    _ssh_keys['changed']
    or _ssh_permit_rootlogin['changed']
    or _ssh_pw_auth['changed']
